name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  # https://github.com/cncf/dcochecker
  dco-check:
    name: DCO signoff check
    # Security! 
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DCO_CHECK_VERBOSE: '1'
          # Comma-separated list of emails that should be ignored during DCO checks
          # DCO_CHECK_EXCLUDE_EMAILS: ${{ inputs.exclude-emails }}
        run: |
          pip3 install -U dco-check
          dco-check
