name: Release

on:
  push:
    branches:
      - main

# TODO: replace with the trigger below when a unit tests workflow exists.
  # workflow_run:
  #   workflows: ["Tests"]
  #   branches: [main]
  #   types:
  #     - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    # TODO: uncomment below when a unit tests workflow exists.
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @google/semantic-release-replace-plugin
